<script type="text/javascript" language="javascript" class="init">
	$(document).ready(function() {
		$('#tipoNotificacion').DataTable();
		$('.edit').hide();		
	} );

	function guardarCambio(){
		$('#form1').attr('action', "/comercial/notificacion/editTipoNotif");
		$('#form1').submit();
	}
	function cancelar(){
		$('#form1').attr('action', "/comercial/notificacion/tipoNotificacion");
		$('#form1').submit();
	}
	<?php echo $this->view->js;?>
</script>
<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
echo $this->view->botones;
echo $this->view->tabla;
?>