<?php

echo $this->getContent();
$error = $this->session->get("error");
if($error != "" || $error != null){
	echo "<div id='error' style='color:red' align='center'>$error</div>";
}
echo $this->tag->form(array("index/entrar",  'enctype' => 'multipart/form-data', 'class' => 'login'));
?>

<div class="logo"><img alt="logo" src="images/logo.png"></div>
  
  <fieldset>
    
  	<legend class="legend">Inicio de Sesi&oacute;n</legend>
    
    <div class="input">
    	<?php 
    	echo $this->tag->textField(array("user", "placeholder" => 'Usuario')); 
    	?>    	
      <span><i class="fa fa-user"></i></span>
    </div>
    
    <div class="input">
    	<?php 
    	echo $this->tag->passwordField(array("pass", 'placeholder' => 'Password'));
    	?>    	
      <span><i class="fa fa-lock"></i></span>
    </div>
    
    <button type="submit" class="submit"><i class="fa fa-long-arrow-right"></i></button>  
    
  </fieldset>    
  
</form>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src="js/index.js"></script>