<body>

    
<?php echo $this->tag->form(array("index/entrar",  'enctype' => 'multipart/form-data', 'class' => 'login')); //, 'class' => 'login' ?>
 <div class="logo"><img alt="logo" src="images/logo.png"></div> 
  <fieldset>
    
  	<legend class="legend">Inicio de Sesi&oacute;n</legend>
    
    <div class="input">
    	<?php echo $this->tag->textField(array("user", "placeholder" => 'Usuario')); 
    	//<input type="text" placeholder="Usuario" required id="user" class="user" />
    	?>    	
      <span><i class="fa fa-user"></i></span>
    </div>
    
    <div class="input">
    	<?php echo $this->tag->passwordField(array("pass", 'placeholder' => 'Password'));
    	//<input type="password" placeholder="Contrase&ntilde;a" required id="pass" class="pass"/>
    	?>    	
      <span><i class="fa fa-lock"></i></span>
    </div>
    <p align="center"><?php echo $this->getContent(); ?></p>
    <button type="submit" class="submit"><i class="fa fa-long-arrow-right"></i></button>    
    
    
    
  </fieldset>    
  
</form>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

        <script src="js/index.js"></script>

    
    
    
</body>