<script type="text/javascript" language="javascript" class="init">
	$(document).ready(function() {
		$('#titems').DataTable();	
		$('.edit').hide();	
		var texto = $('#listProv').val();
		listDept = texto.split(";");
		 $("#proveedor").autocomplete({
			    source:[listDept]
			  });
	} );

	<?php echo $this->view->js;?>
</script>
<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
echo $this->view->botones;
echo $this->view->tabla;
?>