<script type="text/javascript" language="javascript" class="init">
	$(document).ready(function() {
		$('#credito').DataTable();
		$('#titems').DataTable();
		$('.edit').hide();		
	} );

	function addValor(id) {
		var checkedValues = $('.cbitems:checked').map(function() {
		    return this.value;
		}).get();

		var boxes; // = checkedValues.values();
		var tb = "";
		var i;
		for (i = 0; i < checkedValues.length; i++) {
			var f = "#n" + checkedValues[i];
			tb += $(f).val() + ",";
		}
		tb = tb.substring(0, tb.length-1);
		//alert(tb);
		
		$.ajax({
			type: "POST",
			url: "credito/calcular", 
			data: {cuotas: $('#cuotas').val(), item: id, monto: $('#monto').val(), prima: $('#prima').val(), cb: checkedValues, tbox: tb},
			dataType: "json",
			success: function(result){
				var jsondata = jQuery.parseJSON(JSON.stringify(result)); 
				$("#monto").val(jsondata.monto);
				$("#prima").val(jsondata.prima);				
			}});
	};
	
	<?php echo $this->view->js;?>
</script>
<style>
.ditems {
    position: relative;
    clear: both;
    width: 90%;
    left: 110px;
}
</style>
<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
echo $this->view->botones;
echo $this->view->tabla;
?>